### ISSUE TITLE
Deal making using one-off schedule w/ SQLite

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#110]
## Prerequisite
- [ ] Have some dataset prepared
- [ ] Have the dataset associated with a wallet #106 

# Test List
- [ ] Run deal making service `singularity run dealmaker`
- [ ] Run deal tracking service `singularity run deal-tracker`
- [ ] Use `singularity deal schedule create` to send deals from a dataset to a single storage provider in one go
  - [ ] Do not set any options in "Restrictions" . It will be covered in #109
  - [ ] Do not set any options in "Scheduling". It will be covered in #108
  - [ ] No need to test different combination of options in "Deal Proposal" as it is already covered in #107
- [ ] `singularity deal schedule list` to list all current schedules
  - [ ] Should be marked complete when all deals are sent out
- [ ] `singularity deal pause` to pause the current schedule - takes a few seconds to take effect
- [ ] `singularity deal resume` to resume the current schedule - takes a few seconds to take effect
- [ ] After the storage provider have published / sealed some deals, check the deal status using `singularity deal list`

**Comment by xinaxu** [comment]
covered in unit test
