### ISSUE TITLE
Deal making with data prepared by other tools

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#111]
## Prerequisite
- [ ] Have some dataset populated using external CIDs #105
- [ ] Have the dataset associated with a wallet #106 

# Test List
- [ ] Perform tests described in #110

**Comment by xinaxu** [comment]
covered in unit test
