### ISSUE TITLE
Evaluate all Rclone configurations

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#211]
Not all rclone backend returns reliable last modified time. This can cause an issue where the same item are considered different when the last modified time has changed. This usually happens if reading modified time from backend is a separate network request. If such request failed, Rclone will return the current time. Or a storage backend that does not support last modified time
Examples of backend that requires another network request
* webdav, swift, sugarsync, sharefile, qingstor, premiumizeme, pcloud, mailru, jottacloud, etc
Examples of backend that directly returns time.Now
* uptobox

There is also a Rclone global config that can set to always use server last modified time.
Each backend has a SlowModTime and SlowHash boolean that tells whether this requires additional network request to get the last modified time
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/singularity/issues/316
- [ ] https://github.com/data-preservation-programs/singularity/issues/220
- [ ] https://github.com/data-preservation-programs/singularity/issues/317
- [ ] https://github.com/data-preservation-programs/singularity/issues/318
- [ ] https://github.com/data-preservation-programs/singularity/issues/319
- [ ] https://github.com/data-preservation-programs/singularity/issues/320
```

**Comment by xinaxu** [comment]
Proposing below handling of different Rclone features
* WriteMimeType - setting mime to `application/car` for exported CAR files
* CanHaveEmptyDirectories - relates to #220 
* SlowModTime - It's fine to use it, at least for S3, as long as `UseServerModTime` is set to true
* SlowHash - will not attempt to hash the file and treat hash value as empty string

**Comment by xinaxu** [comment]
relates to #304 , if we want to skip additional request when reading S3 objects, we will need to
1. specify no-head-object for the s3 storage, this way Rclone won't issue another head request to get the hash or last modified when reading the object
2. specify read-only/no-check for the storage, this way Singularity will not compare hash or last modified when packing the data

**Comment by xinaxu** [comment]
Below is evaluation of useful rclone config
* UseServerModTime - should always set to true
* InsecureSkipVerify - should be configurable

**Comment by xinaxu** [comment]
Another observation on request retry. Rclone and S3 SDK both have good enough retry strategy, however, when reading an object, any failure for the http body stream is not retriable.

**Comment by xinaxu** [comment]
Some FS also implements ListR which is to recursively list files from a storage, however, the order of file is not guaranteed and it is not resumable, hence we will not be using this implementation
