### ISSUE TITLE
Performance improvements for remote storage

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#215]
For remote storage, especially lots of small files, we need to measure and improve the performance for
- [x] Scanning can be optimized by listing multiple sub folders concurrently
- [ ] Packing can use multiple workers - need a way to determined the best number of threads
  - [ ] dataset-worker should periodically dump CPU usage, RAM usage, I/O speed for each worker thread
  - [ ] keyboard shortcut to increase / decrease number of workers
  - [x] The current code does not support increasing or decreasing number of workers
- [x] Daggen cannot be optimized
- [x] deprioritied as a separate item #335
```[tasklist]
### Tasks
- [x] Expose UseServerModifiedTime and LowLevelRetry
- [x] Multithreaded dataset scanning
```

**Comment by xinaxu** [comment]
Following below steps, currently getting ~100 files inserted per second
```
singularity storage create s3 aws --region us-east-2 --name fah --path fah-public-data-covid19-absolute-free-energy
```

This dataset has 522925693 files, that will result in 60 days to completely scan the dataset.
All database backend are capable of more than 100 files per second (at least 10x) so it make sense to parallize the scanning process into mutiple threads.

However, This makes last_scanned_path useless - so the user can either
1. set scanning concurrency to 1 and make use of last_scanned_path
2. set scanning concurrency to more than 1 but each scan will restart from beginning

Other things discovered that can improve the performance is
1. config.UseServerModifiedTime to true will skip reading the s3 object metadata
2. config.LowLevelRetry will control number of retries. the user can set to very large to keep retrying
