### ISSUE TITLE
Refactor based on community feedback

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#217]
```[tasklist]
### Tasks
- [x] dashboard
- [x] database
- [x] datasource
- [x] docs
- [x] handler
- [x] migrate
- [x] model
- [x] pack
- [x] replication
- [x] service
- [x] store
- [x] util
- [x] service/contentprovider
- [x] service/datasetworker
- [x] service/dealpusher
- [x] service/dealtracker
- [x] service/epochutil
- [x] service/healthcheck
- [x] pack/push
- [x] handler/storage
- [x] handler/datapre
- [x] handler/deal
- [x] handler/wallet
- [x] handler/tool
- [x] api
- [x] cmd
- [ ] https://github.com/data-preservation-programs/singularity/issues/241
- [ ] https://github.com/data-preservation-programs/singularity/issues/245
- [ ] https://github.com/data-preservation-programs/singularity/issues/244
- [ ] https://github.com/data-preservation-programs/singularity/issues/243
- [ ] https://github.com/data-preservation-programs/singularity/issues/242
```
#208
