### ISSUE TITLE
[caro test] singularity starmap root node

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/singularity#222]
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/singularity/issues/217
- [ ] https://github.com/data-preservation-programs/singularity/issues/219
- [ ] https://github.com/data-preservation-programs/singularity/pull/207
- [ ] https://github.com/data-preservation-programs/singularity/issues/218
```
