### ISSUE TITLE
[Feature] Singularity V2 Deal Making Push Mode

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#265]
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/singularity/issues/243
- [ ] https://github.com/data-preservation-programs/singularity/issues/114
- [ ] https://github.com/data-preservation-programs/singularity/issues/235
```

**Comment by anjor** [comment]
@xinaxu @celine3650 
looks like all tasks are complete here? What's pending?

**Comment by xinaxu** [comment]
Closing
