### ISSUE TITLE
[Feature] Singularity V2 Metrics Collection

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#266]
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/singularity/issues/248
- [ ] https://github.com/data-preservation-programs/singularity/issues/247
- [ ] https://github.com/data-preservation-programs/singularity/issues/212
- [ ] https://github.com/data-preservation-programs/singularity/issues/115
- [ ] https://github.com/data-preservation-programs/singularity-metrics-dashboard/issues/2
- [ ] https://github.com/data-preservation-programs/singularity-metrics-dashboard/issues/5
```
