### ISSUE TITLE
[Feature] Performance Push

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/singularity#326]
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/singularity/issues/258
- [ ] https://github.com/data-preservation-programs/singularity/issues/249
- [ ] https://github.com/data-preservation-programs/singularity/issues/304
- [ ] https://github.com/data-preservation-programs/singularity/issues/216
- [ ] https://github.com/data-preservation-programs/singularity/issues/215
- [ ] https://github.com/data-preservation-programs/singularity/issues/143
- [x] CPU and Memory Profiling
- [ ] https://github.com/data-preservation-programs/singularity/issues/161
- [ ] https://github.com/data-preservation-programs/singularity/issues/327
- [ ] https://github.com/data-preservation-programs/singularity/issues/338
```
